# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "timetrap-hipchat"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Logan Koester"]
  s.date = "2014-04-22"
  s.description = "Extends the Timetrap timetracker by providing command hooks to notify a Hipchat room when you clock in/out/resume"
  s.email = ["logan@logankoester.com"]
  s.executables = ["timetrap-hipchat"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "README.md",
    "Rakefile",
    "bin/timetrap-hipchat",
    "demo.png",
    "lib/timetrap/hipchat.rb",
    "lib/timetrap/hipchat/templates/hipchat.yml.tt",
    "lib/timetrap/hipchat/templates/in.rb",
    "lib/timetrap/hipchat/templates/out.rb",
    "lib/timetrap/hipchat/templates/resume.rb",
    "timetrap-hipchat.gemspec"
  ]
  s.homepage = "https://github.com/logankoester/timetrap-hipchat"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "Timetrap hooks to notify a Hipchat room"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<timetrap>, [">= 0"])
      s.add_runtime_dependency(%q<hipchat>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<timetrap>, [">= 0"])
      s.add_dependency(%q<hipchat>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<timetrap>, [">= 0"])
    s.add_dependency(%q<hipchat>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

